export const DEFAULT_JOB_OPENING: NewJobOpening = {
  title: "",
  description: "",
  location: "",
  role: "",
  pay: "",
  payNumeric: 0,
  empBenefits: "",
  company: null,
  jobType: "",
  registrationStart: null,
  registrationEnd: null,
  extraApplicationFields: [],
  hidden: false,
  autoApprove: false,
  autoVisible: false,
  allowSelected: false,
  participatingGroups: [],
};
