import { cookies } from "next/headers";
import { SessionProvider } from "next-auth/react";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"; // or `v14-appRouter` if you are using Next.js v14

import { TRPCReactProvider } from "~/trpc/react";

import ThemeRegistry from "./_utils/theme/ThemeRegistry";

import "~/styles/globals.css";

import "@fontsource/ibm-plex-sans";
import "@fontsource-variable/oswald";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body id="__next">
        <TRPCReactProvider cookies={cookies().toString()}>
          <AppRouterCacheProvider
            options={{
              enableCssLayer: true,
            }}
          >
            <ThemeRegistry options={{ key: "mui-theme", prepend: true }}>
              {children}
            </ThemeRegistry>
          </AppRouterCacheProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
